import fs from 'node:fs';import assert from 'node:assert/strict';
const base='http://127.0.0.1:3001/api/v1',origin='http://127.0.0.1:3000',stamp=Date.now(),checks=[];
const pass=s=>{checks.push(s);console.log('PASS',s)};
async function req(path,body,cookie,status=200){const r=await fetch(`${base}/${path}`,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{Origin:origin,'Content-Type':'application/json'}),...(cookie?{Cookie:cookie}:{})},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();assert.equal(r.status,status,`${path}: ${JSON.stringify(d)}`);return {d,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
const login=async role=>(await req('auth/demo',{role},null,201)).cookie;
const admin=await login('admin'),sale=await login('sale'),other=await login('other');
await req('admin/overview',undefined,null,401);await req('admin/overview',undefined,sale,403);await req('admin/organizations',{},other,403);pass('Admin endpoints reject anonymous and non-admin users');
const org=(await req('admin/organizations',{legal_name:`Doanh nghiệp kiểm thử ${stamp}`,slug:`qa-company-${stamp}`,registration_number:`QA-${stamp}`,country:'VN',introduction:'Hồ sơ kiểm thử nội bộ, không phải doanh nghiệp thật.'},admin,201)).d;
assert.ok(!(await req('directory')).d.organizations.some(o=>o.id===org.id));pass('New company remains pending and private');
await req(`admin/organizations/${org.id}/status`,{status:'active',confirmed:true},admin,201);pass('Admin explicitly activates company');
const project=(await req('admin/projects',{name:`Dự án kiểm thử ${stamp}`,slug:`qa-project-${stamp}`,country:'VN',city:'Thành phố thử nghiệm',address:'Địa chỉ thử nghiệm nội bộ',description:'Thông tin dự án giả lập dùng để kiểm thử cấp combo và quyền đăng tin trong bản local.',types:['villa']},admin,201)).d;await req(`admin/projects/${project.id}/status`,{status:'published'},admin,201);pass('Admin creates project with approved property type');
const invite=(await req(`admin/organizations/${org.id}/invite`,{email:`manager-${stamp}@example.test`,name:'Quản lý kiểm thử'},admin,201)).d;const activation=new URL(invite.activation_url,origin).searchParams.get('token');const manager=(await req('auth/activate',{token:activation,password:'Only-local-tests-2026!'},null,201)).cookie;pass('Invited company manager activates account');
const today=new Date().toISOString().slice(0,10),until=new Date(Date.now()+30*86400000).toISOString().slice(0,10);
function pdf(){const text='BT /F1 14 Tf 40 150 Td (TEST FIXTURE - NOT A REAL CONTRACT) Tj ET';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 420 240] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${text.length} >>\nstream\n${text}\nendstream`];let s='%PDF-1.4\n';const offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(s));s+=`${i+1} 0 obj\n${o}\nendobj\n`;});const start=Buffer.byteLength(s);s+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;return Buffer.from(s);}
async function upload(data){const f=new FormData();for(const [k,v] of Object.entries({organization_id:org.id,contract_number:`QA-CONTRACT-${stamp}`,effective_from:today,effective_until:until,signed_at:today}))f.set(k,v);f.set('file',new Blob([data],{type:'application/pdf'}),'test-contract.pdf');return fetch(`${base}/admin/contracts`,{method:'POST',headers:{Origin:origin,Cookie:admin},body:f});}
assert.equal((await upload(Buffer.from('not a PDF'))).status,400);pass('Non-PDF contract rejected');
const up=await upload(pdf());const contract=await up.json();assert.equal(up.status,201,JSON.stringify(contract));pass('Signed PDF stored as private contract draft');
const combo={contract_id:contract.id,name:'Combo kiểm thử',sale_limit:2,listing_limit:5,projects:[project.id],confirmed:true};await req('admin/subscriptions',combo,admin,400);pass('Combo blocked before contract activation');
const overview=(await req('admin/overview',undefined,admin)).d;const doc=overview.documents.find(d=>d.contract_id===contract.id);assert.ok(doc.available);const docurl=`${base}/admin/documents/${doc.id}`;
for(const [cookie,status] of [[null,401],[sale,404],[other,404],[manager,200],[admin,200]]){const r=await fetch(docurl,{headers:cookie?{Cookie:cookie}:{}});assert.equal(r.status,status);if(status===200){assert.match(r.headers.get('content-disposition'),/attachment/);assert.match(r.headers.get('content-security-policy'),/sandbox/);}}
pass('Private PDF restricted to admin and correct company manager');
await req(`admin/contracts/${contract.id}/status`,{status:'active',confirmed:true},admin,201);const sub=(await req('admin/subscriptions',combo,admin,201)).d;pass('Active signed contract permits scoped combo');
const work=(await req('workspace',undefined,manager)).d;assert.equal(work.subscriptions.length,1);assert.equal(work.grants.length,1);assert.equal(work.grants[0].project_id,project.id);pass('Company manager sees only own combo and project grant');
const sinvite=(await req('workspace/invite',{subscription_id:sub.id,name:'Sale kiểm thử combo',email:`sale-${stamp}@example.test`},manager,201)).d;const stoken=new URL(sinvite.activation_url,origin).searchParams.get('token');const newsale=(await req('auth/activate',{token:stoken,password:'Only-local-tests-2026!'},null,201)).cookie;const w=(await req('workspace',undefined,manager)).d;await req('workspace/assign',{seat_id:w.seats[0].id,grant_id:w.grants[0].id},manager,201);assert.equal((await req('workspace',undefined,newsale)).d.assignments.length,1);pass('New organization can invite Sale and assign newly created project');
await req(`admin/subscriptions/${sub.id}/status`,{status:'suspended'},admin,201);assert.equal((await req('workspace',undefined,newsale)).d.assignments.length,0);pass('Suspended combo immediately removes live posting rights');
await req(`admin/subscriptions/${sub.id}/status`,{status:'active'},admin,201);await req(`admin/contracts/${contract.id}/status`,{status:'suspended',confirmed:true},admin,201);assert.equal((await req('workspace',undefined,newsale)).d.assignments.length,0);pass('Suspended contract immediately removes live posting rights');
const article=(await req('admin/articles',{title:'Bài viết kiểm thử nội bộ',slug:`qa-article-${stamp}`,body:'Nội dung minh họa cho quy trình biên tập, xuất bản và ẩn bài viết trong bản chạy thử.',category:'news',meta_title:'Tiêu đề SEO thử nghiệm',meta_description:'Mô tả SEO thử nghiệm'},admin,201)).d;
await req(`articles/qa-article-${stamp}`,undefined,null,404);await req(`admin/articles/${article.id}/status`,{status:'published'},admin,201);assert.equal((await req(`articles/qa-article-${stamp}`)).d.meta_title,'Tiêu đề SEO thử nghiệm');pass('Draft article private, published article public');
await req('admin/articles',{id:article.id,title:'Không được sửa bài đang công khai',slug:`qa-article-${stamp}`,body:'Nội dung thử nghiệm đủ dài để xác nhận bài đang xuất bản không bị sửa trực tiếp.',category:'news'},admin,400);pass('Published article cannot be edited until hidden');
await req(`admin/articles/${article.id}/status`,{status:'draft'},admin,201);await req(`articles/qa-article-${stamp}`,undefined,null,404);pass('Hiding article removes public content');
await req(`admin/articles/${article.id}/status`,{status:'archived'},admin,201);await req(`admin/organizations/${org.id}/status`,{status:'suspended',confirmed:true},admin,201);await req(`admin/projects/${project.id}/status`,{status:'suspended'},admin,201);
fs.writeFileSync('tests/admin-result.json',JSON.stringify({at:new Date().toISOString(),passed:checks.length,checks,fixture:{org:org.id,project:project.id,contract:contract.id,subscription:sub.id,article:article.id}},null,2));console.log(`${checks.length} admin workflow checks passed.`);
