const {chromium}=require('C:/Users/NHU ANH/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs');const path=require('path');const assert=require('assert/strict');
(async()=>{const dir=path.resolve(process.argv[2]||'qa');const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:3000/dang-nhap');await page.getByRole('button',{name:'Đăng ký',exact:true}).click();await page.getByRole('dialog').waitFor();assert.match(await page.getByRole('dialog').innerText(),/Vui lòng liên hệ/);await page.getByRole('button',{name:'Đã hiểu'}).click();
await page.getByRole('button',{name:'Sale',exact:true}).click();await page.getByRole('heading',{name:'Chào bạn, bắt đầu ngày mới!'}).waitFor();await page.getByRole('button',{name:'Tạo tin mới',exact:true}).click();const form=page.locator('.create-panel form');await form.locator('[name=assignment_id]').selectOption({label:'The Garden Riverside'});await form.locator('[name=title]').fill('Tin kiểm thử giao diện điện thoại cho biệt thự');await form.locator('[name=price_amount]').fill('9500000000');await form.locator('[name=area_m2]').fill('180');await form.locator('[name=description]').fill('Mô tả căn biệt thự dùng để kiểm tra thao tác soạn và chỉnh sửa trên điện thoại. Đây là dữ liệu kiểm thử.');await page.getByRole('button',{name:'Lưu bản nháp',exact:true}).click();await page.getByText('Đã lưu bản nháp. Thêm ít nhất một ảnh trước khi gửi duyệt.').waitFor();
const row=page.locator('.workspace-listing').filter({hasText:'Tin kiểm thử giao diện điện thoại cho biệt thự'});await row.getByRole('button',{name:'Chỉnh sửa',exact:true}).click();await page.locator('.editor-modal input[name=title]').waitFor();await page.locator('.editor-modal input[name=title]').fill('Bản nháp trải nghiệm trên điện thoại đã chỉnh sửa');await page.getByRole('button',{name:'Lưu chỉnh sửa',exact:true}).click();await page.locator('.editor-modal').waitFor({state:'detached'});await page.getByRole('heading',{name:'Bản nháp trải nghiệm trên điện thoại đã chỉnh sửa'}).first().waitFor();
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(dir,'390-workspace-sale.png'),fullPage:true});
await page.getByRole('button',{name:'Đăng xuất',exact:true}).click();await page.getByRole('button',{name:'Doanh nghiệp',exact:true}).click();await page.getByRole('button',{name:'Đội ngũ & combo',exact:true}).click();await page.getByRole('heading',{name:'Thành viên doanh nghiệp'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(dir,'390-workspace-company.png'),fullPage:true});
await page.getByRole('button',{name:'Đăng xuất',exact:true}).click();await page.getByRole('button',{name:'Quản trị',exact:true}).click();await page.getByRole('heading',{name:'Quản lý nội dung đăng tin'}).waitFor();await page.locator('.workspace-listing').filter({hasText:'Sở hữu biệt thự tại The Garden Riverside'}).getByRole('button',{name:'Chi tiết',exact:true}).click();await page.locator('.editor-modal img').first().waitFor();await page.screenshot({path:path.join(dir,'390-moderation-detail.png'),fullPage:true});await page.getByRole('button',{name:'Đóng',exact:true}).click();
await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:path.join(dir,'1440-workspace-admin.png'),fullPage:true});
fs.writeFileSync(path.join(dir,'workflow-results.json'),JSON.stringify({passed:9,checks:['Registration notice','Demo Sale login','Create draft on mobile','Edit draft','Sale mobile no overflow','Company login','Company mobile no overflow','Admin login','Review listing images before approval'],errors},null,2));console.log('9 browser workflow checks passed',errors);await browser.close();})().catch(e=>{console.error(e);process.exit(1)});

